config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root to: 'home#index'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'spots_data', to: 'home#spots_data'
  get 'about', to: 'about#index'

  resource :users do
    collection do
      get 'activate'
      get 'delete_confirm'
      get 'list'
      get 'spots'
      get 'comments'
      delete 'remove'
    end
  end
  resources :spots do
    resources :comments, shallow: true, only: %i[create destroy]
    collection do
      get 'list'
      get 'favorites'
      get 'search'
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :email_changes, only: %i[create] do
    collection do
      get 'confirm'
    end
  end
  resources :password_resets, only: %i[new create edit update]
  resources :search_places, only: %i[index create]
end

app/models/spot.rb
class Spot < ApplicationRecord
  has_many :spots_pumps, dependent: :destroy
  has_many :spots_valves, dependent: :destroy
  has_many :pumps, through: :spots_pumps
  has_many :valves, through: :spots_valves
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user, optional: true

  accepts_nested_attributes_for :spots_pumps, allow_destroy: true
  accepts_nested_attributes_for :spots_valves, allow_destroy: true

  enum fee: { free: 0, paid: 1 }

  validates :name, presence: true, length: { maximum: 255 }
  validates :fee, presence: true, inclusion: { in: Spot.fees.keys }
  validates :address_prefecture, presence: true
  validates :address_city, presence: true
  validates :address_detail, presence: true, uniqueness: true, format: { with: /\p{Hiragana}+|\p{Katakana}+|\p{Han}+/ }
  validates :latitude, presence: true, uniqueness: { scope: :longitude }
  validates :longitude, presence: true
  validate :must_have_at_least_one_pump
  validate :must_have_at_least_one_valve
  validate :check_opening_and_closing_times

  private

  def must_have_at_least_one_pump
    if spots_pumps.reject(&:marked_for_destruction?).blank?
      errors.add(:spots_pumps, '空気入れの使用方法を一つ以上選択してください')
    end
  end

  def must_have_at_least_one_valve
    if spots_valves.reject(&:marked_for_destruction?).blank?
      errors.add(:spots_valves, 'バルブの形状を一つ以上選択してください')
    end
  end

  def check_opening_and_closing_times
    if opening_time.present? && closing_time.blank?
      errors.add(:closing_time, '営業開始時間を入力した場合は、営業終了時間も入力してください')
    elsif opening_time.blank? && closing_time.present?
      errors.add(:opening_time, '営業終了時間を入力した場合は、営業開始時間も入力してください')
    end
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  skip_before_action :require_login, except: %i[destroy list favorites]

  def index
    @q = Spot.ransack(params[:q])
    @spots = @q.result(distinct: true).page(params[:page]).order(created_at: :desc)
  end

  def show
    @spot = Spot.find(params[:id])
    @comment = Comment.new
    @comments = @spot.comments.order(created_at: :asc)
  end

  def new
    @spot = Spot.new

    @pumps = Pump.all
    @valves = Valve.all

    @lat = params[:lat]
    @lng = params[:lng]
    result = Geocoder.search([@lat, @lng]).first

    address = result.address # 住所全体 (郵便番号、国名を含む)

    @prefecture = extract_address_component(result, 'administrative_area_level_1') # 都道府県

    ward = extract_address_component(result, 'administrative_area_level_2') # 郡
    city = extract_address_component(result, 'locality') # 市区町村 (区は東京都の特別区)
    if ward
      @city = "#{ward}#{city}" # 郡と町村を結合
    else
      @city = city # 郡がない場合は市または特別区のみ
    end

    # 住所全体から郵便番号、国名、都道府県、市区町村を取り除く
    postal_code = extract_address_component(result, 'postal_code') # 郵便番号
    @country = extract_address_component(result, 'country') # 国名
    [postal_code, @country, @prefecture, @city].compact.each do |item|
      address.gsub!(/#{item}/, '')
    end
    @address_detail = address.gsub(/、〒\s*/, '').strip

    @full_address = "#{@prefecture}#{@city}#{@address_detail}" # 住所全体 (郵便番号、国名を含まない)
  end

  def create
    params_without_country = spot_params.except(:country)
    @spot = Spot.new(params_without_country)
    @spot.user_id = current_user.id if current_user

    if spot_params[:country] == '日本' && @spot.save
      flash[:success] = t('helpers.flash.spot.register.success')
      redirect_to spot_path(@spot)
    else
      @pumps = Pump.all
      @valves = Valve.all

      @prefecture = @spot.address_prefecture
      @city = @spot.address_city
      @address_detail = @spot.address_detail
      @full_address = @spot.decorate.full_address
      @lat = @spot.latitude
      @lng = @spot.longitude
      @country = spot_params[:country]

      case 
      when @country != '日本'
        flash.now[:danger] = t('helpers.flash.spot.register.japan_only')
      when @spot.errors.include?(:address_detail)
        flash.now[:danger] = t('helpers.flash.spot.register.invalid_address')
      when @spot.errors.include?(:latitude)
        flash.now[:danger] = t('helpers.flash.spot.register.overlap')
      else
        flash.now[:danger] = t('helpers.flash.spot.register.failure')
      end
      render :new
    end
  end

  def edit
    @spot = Spot.find(params[:id])

    @pumps = Pump.all
    @valves = Valve.all
  end

  def update
    @spot = Spot.find(params[:id])

    if @spot.update(spot_params)
      flash[:success] = t('helpers.flash.spot.update.success')
      redirect_to spot_path(@spot)
    else
      @pumps = Pump.all
      @valves = Valve.all

      flash.now[:danger] = t('helpers.flash.spot.update.failure')
      render :edit
    end
  end

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy!
    flash[:success] = t('helpers.flash.spot.destroy')
    redirect_to spots_path
  end

  def list
    @spots = current_user.spots.page(params[:page]).order(created_at: :desc)
  end

  def favorites
    @spots = Spot.joins(:favorites).where(favorites: { user_id: current_user.id }).order('favorites.created_at DESC').page(params[:page])
  end

  def search
    @q = Spot.ransack(params[:q])

    @pumps = Pump.all
    @valves = Valve.all
  end

  private

  def extract_address_component(result, type)
    component = result.data['address_components'].find { |c| c['types'].include?(type) }
    component['long_name'] if component
  end

  def spot_params
    allowed_params = params.require(:spot).permit(
      :name,
      :fee,
      :opening_time,
      :closing_time,
      :address_prefecture,
      :address_city,
      :address_detail,
      :latitude,
      :longitude,
      :country,
      spots_pumps_attributes: [:pump_id, :id, :_destroy],
      spots_valves_attributes: [:valve_id, :id, :_destroy]
    )
    allowed_params[:fee] = allowed_params[:fee].to_i
    allowed_params
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/edit.html.erb
<% content_for :title do %>
  <title><%= @spot.name %> | 自転車空気入れマップ</title>
<% end %>

<main class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto mt-3 mb-5">
      <h1>施設情報更新</h1>
      <%= form_with model: @spot, local: true do |f| %>
        <div class="mb-3">
          <%= f.label :name, class: 'form-label text-secondary' %>
          <%= f.text_field :name, class: 'form-control' %>

          <% if @spot.errors.include?(:name) %>
            <p class="text-danger"><%= @spot.errors[:name].first %></p>
          <% end %>
        </div>

        <div class="mb-3">
          <%= f.label '住所', class: 'form-label text-secondary' %>
          <p class="ms-3"><%= @spot.decorate.full_address %></p>
        </div>

        <div class="mb-3 row">
          <%= f.label :fee, class: 'form-label text-secondary', for: nil %>
          <% Spot.fees.each do |fee_key, fee_value| %>
            <div class="col-12 col-md mb-2">
              <%= f.radio_button :fee, fee_value, checked: fee_key == @spot.fee %>
              <%= f.label "fee_#{fee_value}", Spot.fees_i18n[fee_key] %>
            </div>
          <% end %>
        </div>

        <div class="mb-3 row">
          <%= f.label '空気入れの使用方法（一つ以上選択必須）', class: 'form-label text-secondary', for: nil %>
          <% @pumps.each do |pump| %>
            <% spots_pump = @spot.spots_pumps.find_or_initialize_by(pump_id: pump.id) %>
            <%= f.fields_for :spots_pumps, spots_pump do |spots_pump_form| %>
              <div class="col-12 col-md mb-2">
                <% checkbox_id = "pump_#{pump.id}" %>
                <%= spots_pump_form.check_box :_destroy, { id: checkbox_id, checked: !spots_pump_form.object.new_record? && !spots_pump_form.object.marked_for_destruction?, inverted: true }, "0", "1" %>
                <%= spots_pump_form.label :_destroy, pump.usage, for: checkbox_id %>
                <%= spots_pump_form.hidden_field :pump_id, value: pump.id %>
              </div>
            <% end %>
          <% end %>

          <% if @spot.errors.include?(:spots_pumps) %>
            <p class="text-danger"><%= @spot.errors[:spots_pumps].first %></p>
          <% end %>
        </div>

        <div class="mb-3 row">
          <%= f.label '対応するバルブの形状（一つ以上選択必須）', class: 'form-label text-secondary', for: nil %>
          <p style="font-size: 12px;">
            ※英式は主にシティサイクル（いわゆるママチャリ）、米式は主にマウンテンバイク、仏式は主にロードバイク・クロスバイクに使われます。<a href="https://www.cso.co.jp/chishiki/img/barub.gif" class="text-decoration-none">こちらの画像</a>を参考にしてください。よくわからない場合は「英式」で登録してください。
          </p>
          <% @valves.each do |valve| %>
            <% spots_valve = @spot.spots_valves.find_or_initialize_by(valve_id: valve.id) %>
            <%= f.fields_for :spots_valves, spots_valve do |spots_valve_form| %>
              <div class="col-12 col-md mb-2">
                <% checkbox_id = "valve_#{valve.id}" %>
                <%= spots_valve_form.check_box :_destroy, { id: checkbox_id, checked: !spots_valve_form.object.new_record? && !spots_valve_form.object.marked_for_destruction?, inverted: true }, "0", "1" %>
                <%= spots_valve_form.label :_destroy, valve.kind, for: checkbox_id %>
                <%= spots_valve_form.hidden_field :valve_id, value: valve.id %>
              </div>
            <% end %>
          <% end %>

          <% if @spot.errors.include?(:spots_valves) %>
            <p class="text-danger"><%= @spot.errors[:spots_valves].first %></p>
          <% end %>
        </div>

        <div class="mb-3">
          <%= f.label '施設の営業時間（任意）', class: 'form-label text-secondary', for: nil %>
          <%= f.time_field :opening_time, class: 'form-control' %>
          <p class="text-center mb-0">〜</p>
          <%= f.time_field :closing_time, class: 'form-control' %>

          <% if @spot.errors.include?(:opening_time) %>
            <p class="text-danger"><%= @spot.errors[:opening_time].first %></p>
          <% elsif @spot.errors.include?(:closing_time) %>
            <p class="text-danger"><%= @spot.errors[:closing_time].first %></p>
          <% end %>
        </div>

        <%= f.submit t('helpers.submit.update'), class: 'btn btn-primary col-12 col-lg-2' %>
      <% end %>
      <div class="row">
        <% if logged_in? && (current_user.admin? || current_user.spots.exists?(@spot.id)) %>
          <%= link_to spot_path(@spot), method: :delete, class: 'col-lg-auto ms-lg-auto', data: { confirm: '本当に削除してよろしいですか？' } do %>
            <button class="btn btn-danger col-12 mt-3">削除</button>
          <% end %>
        <% else %>
        <!--未実装-->
          <!--<%= link_to '#', class: 'col-lg-auto ms-lg-auto' do %>
            <button class="btn btn-danger col-12 mt-3">削除依頼</button>
          <% end %>-->
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/spots/favorites.html.erb
<% content_for :title do %>
  <title>お気に入り | 自転車空気入れマップ</title>
<% end %>

<main class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto mt-3 mb-5">
      <h1>お気に入り</h1>
      <p>登録件数：<%= @spots.total_count %>件</p>
      <% if @spots.total_count == 0 %>
        <p>お気に入りに登録した施設はありません。</p>
      <% else %>
        <ul class="p-0">
          <% @spots.each do |spot| %>
            <li class="card border-0 hover-card">
              <div class="card-body row">
                <div class="col-11">
                  <%= link_to spot_path(spot), class: 'text-decoration-none' do %>
                    <p class="card-text text-black"><%= spot.name %></p>
                    <p class="card-text text-secondary"><%= spot.decorate.full_address %></p>
                  <% end %>
                </div>
                <div class="col-1">
                  <%= render partial: 'favorites/favorite_button', locals: { spot: spot } %>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
        <div class="d-flex justify-content-center">
          <%= paginate @spots, theme: 'bootstrap-5' %>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/spots/index.html.erb
<% content_for :title do %>
  <title>施設一覧 | 自転車空気入れマップ</title>
<% end %>

<main class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto mt-3 mb-5">
      <h1>施設一覧</h1>
      <div class="mb-3">
        <%= search_form_for @q do |f| %>
          <div class="row">
            <div class="col-9 col-md-11">
              <%= f.search_field :name_or_address_prefecture_or_address_city_or_address_detail_cont, class: 'form-control', placeholder: '施設名・地名' %>
            </div>
            <div class="col-3 col-md-1">
              <%= f.submit t('helpers.submit.search'), class: 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
      </div>
      <p>検索結果：<%= @spots.total_count %>件</p>
      <% if @spots.total_count == 0 %>
        <p>検索条件に一致する施設はありませんでした。</p>
      <% else %>
        <ul class="p-0">
          <% @spots.each do |spot| %>
            <li class="card border-0 hover-card">
              <div class="card-body row">
                <div class="col-11">
                  <%= link_to spot_path(spot), class: 'text-decoration-none' do %>
                    <p class="card-text text-black"><%= spot.name %></p>
                    <p class="card-text text-secondary"><%= spot.decorate.full_address %></p>
                  <% end %>
                </div>
                <div class="col-1">
                  <%= render partial: 'favorites/favorite_button', locals: { spot: spot } %>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
        <div class="d-flex justify-content-center">
          <%= paginate @spots, theme: 'bootstrap-5' %>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/spots/list.html.erb
<% content_for :title do %>
  <title>登録した施設 | 自転車空気入れマップ</title>
<% end %>

<main class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto mt-3 mb-5">
      <h1>あなたの登録した施設</h1>
      <p>登録件数：<%= @spots.total_count %>件</p>
      <% if @spots.total_count == 0 %>
        <p>あなたが登録した施設はありません。</p>
      <% else %>
        <ul class="p-0">
          <% @spots.each do |spot| %>
            <li class="card border-0 hover-card">
              <div class="card-body row">
                <div class="col-11">
                  <%= link_to spot_path(spot), class: 'text-decoration-none' do %>
                    <p class="card-text text-black"><%= spot.name %></p>
                    <p class="card-text text-secondary"><%= spot.decorate.full_address %></p>
                  <% end %>
                </div>
                <div class="col-1">
                  <%= render partial: 'favorites/favorite_button', locals: { spot: spot } %>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
        <div class="d-flex justify-content-center">
          <%= paginate @spots, theme: 'bootstrap-5' %>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/spots/new.html.erb
<% content_for :title do %>
  <title>施設登録 | 自転車空気入れマップ</title>
<% end %>

<main class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto mt-3 mb-5">
      <h1>施設登録</h1>
      <%= form_with model: @spot, local: true do |f| %>
        <%= f.hidden_field :address_prefecture, value: @prefecture %>
        <%= f.hidden_field :address_city, value: @city %>
        <%= f.hidden_field :address_detail, value: @address_detail %>
        <%= f.hidden_field :latitude, value: @lat %>
        <%= f.hidden_field :longitude, value: @lng %>
        <%= f.hidden_field :country, value: @country %>

        <div class="mb-3">
          <%= f.label :name, class: 'form-label text-secondary' %>
          <%= f.text_field :name, class: 'form-control' %>

          <% if @spot.errors.include?(:name) %>
            <p class="text-danger"><%= @spot.errors[:name].first %></p>
          <% end %>
        </div>

        <div class="mb-3">
          <%= f.label '住所', class: 'form-label text-secondary' %>
          <p class="ms-3"><%= @full_address %></p>
        </div>

        <div class="mb-3 row">
          <%= f.label :fee, class: 'form-label text-secondary', for: nil %>
          <% Spot.fees.each do |fee_key, fee_value| %>
            <div class="col-12 col-md mb-2">
              <%= f.radio_button :fee, fee_value, checked: fee_key == "free" %>
              <%= f.label "fee_#{fee_value}", Spot.fees_i18n[fee_key] %>
            </div>
          <% end %>
        </div>

        <div class="mb-3 row">
          <%= f.label '空気入れの使用方法（一つ以上選択必須）', class: 'form-label text-secondary', for: nil %>
          <% @pumps.each_with_index do |pump, index| %>
            <div class="col-12 col-md mb-2">
              <%= check_box_tag 'spot[spots_pumps_attributes][][pump_id]', pump.id, @spot.spots_pumps.map(&:pump_id).include?(pump.id), id: "spot_spots_pumps_attributes_#{index}_pump_id" %>
              <%= label_tag "spot_spots_pumps_attributes_#{index}_pump_id", pump.usage %>
            </div>
          <% end %>

          <% if @spot.errors.include?(:spots_pumps) %>
            <p class="text-danger"><%= @spot.errors[:spots_pumps].first %></p>
          <% end %>
        </div>

        <div class="mb-3 row">
          <%= f.label '対応するバルブの形状（一つ以上選択必須）', class: 'form-label text-secondary', for: nil %>
          <p style="font-size: 12px;">
            ※英式は主にシティサイクル（いわゆるママチャリ）、米式は主にマウンテンバイク、仏式は主にロードバイク・クロスバイクに使われます。<a href="https://www.cso.co.jp/chishiki/img/barub.gif" class="text-decoration-none">こちらの画像</a>を参考にしてください。よくわからない場合は「英式」で登録してください。
          </p>
          <% @valves.each_with_index do |valve, index| %>
            <div class="col-12 col-md mb-2">
              <%= check_box_tag 'spot[spots_valves_attributes][][valve_id]', valve.id, @spot.spots_valves.map(&:valve_id).include?(valve.id), id: "spot_spots_valves_attributes_#{index}_valve_id" %>
              <%= label_tag "spot_spots_valves_attributes_#{index}_valve_id", valve.kind %>
            </div>
          <% end %>

          <% if @spot.errors.include?(:spots_valves) %>
            <p class="text-danger"><%= @spot.errors[:spots_valves].first %></p>
          <% end %>
        </div>

        <div class="mb-3">
          <%= f.label '施設の営業時間（任意）', class: 'form-label text-secondary', for: nil %>
          <%= f.time_field :opening_time, class: 'form-control' %>
          <p class="text-center mb-0">〜</p>
          <%= f.time_field :closing_time, class: 'form-control' %>

          <% if @spot.errors.include?(:opening_time) %>
            <p class="text-danger"><%= @spot.errors[:opening_time].first %></p>
          <% elsif @spot.errors.include?(:closing_time) %>
            <p class="text-danger"><%= @spot.errors[:closing_time].first %></p>
          <% end %>
        </div>

        <%= f.submit t('helpers.submit.register'), class: 'btn btn-primary col-12 col-lg-2' %>
      <% end %>
    </div>
  </div>
</main>

app/views/spots/search.html.erb
<% content_for :title do %>
  <title>施設検索 | 自転車空気入れマップ</title>
<% end %>

<main class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto mt-3 mb-5">
      <h1>空気入れ貸出し施設検索</h1>
      <%= search_form_for @q do |f| %>
        <div class="mb-3">
          <%= f.label :name_or_address_prefecture_or_address_city_or_address_detail_cont, '施設名・地名', class: 'form-label text-secondary' %>
          <%= f.search_field :name_or_address_prefecture_or_address_city_or_address_detail_cont, class: 'form-control' %>
        </div>

        <div class="mb-3 row">
          <%= f.label :fee_in, '貸出し料金', class: 'form-label text-secondary', for: nil %>
          <% Spot.fees.each do |fee_key, fee_value| %>
            <div class="col-12 col-md mb-2">
              <%= f.check_box :fee_in, { multiple: true }, fee_value, nil %>
              <%= f.label "fee_in_#{fee_value}", Spot.fees_i18n[fee_key] %>
            </div>
          <% end %>
        </div>

        <div class="mb-3 row">
          <%= f.label :spots_pumps_pump_id_in, '空気入れの使用方法', class: 'form-label text-secondary', for: nil %>
          <% @pumps.each_with_index do |pump, index| %>
            <div class="col-12 col-md mb-2">
              <%= check_box_tag 'q[spots_pumps_pump_id_in][]', pump.id, false, id: "spots_pumps_pump_id_in_#{index}" %>
              <%= label_tag "spots_pumps_pump_id_in_#{index}", pump.usage %>
            </div>
          <% end %>
        </div>

        <div class="mb-3 row">
          <%= f.label :spots_valves_valve_id_in, '対応するバルブの形状', class: 'form-label text-secondary', for: nil %>
          <p style="font-size: 12px;">
            ※英式は主にシティサイクル（いわゆるママチャリ）、米式は主にマウンテンバイク、仏式は主にロードバイク・クロスバイクに使われます。<a href="https://www.cso.co.jp/chishiki/img/barub.gif" class="text-decoration-none">こちらの画像</a>を参考にしてください。
          </p>
          <% @valves.each_with_index do |valve, index| %>
            <div class="col-12 col-md mb-2">
              <%= check_box_tag 'q[spots_valves_valve_id_in][]', valve.id, false, id: "spots_valves_valve_id_in_#{index}" %>
              <%= label_tag "spots_valves_valve_id_in_#{index}", valve.kind %>
            </div>
          <% end %>
        </div>

        <%= f.submit t('helpers.submit.search'), class: 'btn btn-primary col-12 col-lg-2' %>
      <% end %>
    </div>
  </div>
</main>

app/views/spots/show.html.erb
<% content_for :title do %>
  <title><%= @spot.name %> | 自転車空気入れマップ</title>
<% end %>

<main class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto mt-3 mb-5">
      <div class="row">
        <h1 class="col-12 col-md">施設情報</h1>
        <div class="col-12 col-md-auto mx-0 row">
          <p class="text-secondary col-12 col-md-auto text-end">登録日時：<%= @spot.created_at.strftime('%Y/%m/%d %H:%M') %><%= ' *' if @spot.user_id == nil %></p>
          <%= link_to edit_spot_path(@spot), class: 'col-12 col-md text-end' do %>
            <button class="btn btn-primary">編集</button>
          <% end %>
        </div>
      </div>
      <div>
        <p class="text-secondary">施設名</p>
        <div class="row">
          <div class="col-10">
            <p class="ms-3"><%= @spot.name %></p>
          </div>
          <div class="col-2">
            <%= render partial: 'favorites/favorite_button', locals: { spot: @spot } %>
          </div>
        </div>
      </div>
      <div>
        <p class="text-secondary">住所</p>
        <div class="row">
          <div class="col-9 col-md-auto">
            <p class="ms-3"><%= @spot.decorate.full_address %></p>
          </div>
          <div class="col-3 col-md">
            <%= link_to "https://www.google.com/maps/dir/?api=1&destination=#{@spot.decorate.full_address}", target: "_blank" do %>
              <button class="btn btn-primary">地図</button>
            <% end %>
          </div>
        <div>
      </div>
      <div>
        <p class="text-secondary">貸出し料金</p>
        <p class="ms-3"><%= @spot.fee_i18n %></p>
      </div>
      <div>
        <p class="text-secondary">空気入れの使用方法</p>
        <p class="ms-3"><%= @spot.pumps.map(&:usage).join('、') %></p>
      </div>
      <div>
        <p class="text-secondary">対応するバルブの形状</p>
        <p style="font-size: 12px;">
          ※英式は主にシティサイクル（いわゆるママチャリ）、米式は主にマウンテンバイク、仏式は主にロードバイク・クロスバイクに使われます。<a href="https://www.cso.co.jp/chishiki/img/barub.gif" class="text-decoration-none">こちらの画像</a>を参考にしてください。
        </p>
        <p class="ms-3"><%= @spot.valves.map(&:kind).join('、') %></p>
      </div>
      <div>
        <p class="text-secondary">施設の営業時間</p>
        <% if @spot.opening_time.nil? || @spot.closing_time.nil? %>
          <p class="ms-3">未登録</p>
        <% else %>
          <p class="ms-3"><%= @spot.opening_time.strftime('%k:%M') %> 〜 <%= @spot.closing_time.strftime('%k:%M') %></p>
        <% end %>
      </div>
      <div>
        <p class="text-secondary">コメント</p>
        <div id="comments_container">
          <% @comments.each do |comment| %>
            <%= render partial: 'comments/comment', locals: { comment: comment } %>
          <% end %>
        </div>
      </div>
      <div>
        <%= form_with model: @comment, url: spot_comments_path(@spot), local: false do |f| %>
          <%= f.hidden_field :spot_id, value: @spot.id %>
          <div class="mb-3">
            <%= f.text_area :content, class: 'form-control', id: "comment_content", placeholder: 'コメントを入力してください', required: true %>
          </div>
          <div class="mb-3">
            <%= f.submit t('helpers.submit.post'), class: 'btn btn-primary col-12 col-lg-2' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>