config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root to: 'home#index'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'spots_data', to: 'home#spots_data'
  get 'about', to: 'about#index'

  resource :users do
    collection do
      get 'activate'
      get 'delete_confirm'
      get 'list'
      get 'spots'
      get 'comments'
      delete 'remove'
    end
  end
  resources :spots do
    resources :comments, shallow: true, only: %i[create destroy]
    collection do
      get 'list'
      get 'favorites'
      get 'search'
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :email_changes, only: %i[create] do
    collection do
      get 'confirm'
    end
  end
  resources :password_resets, only: %i[new create edit update]
  resources :search_places, only: %i[index create]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :spot

  validates :user_id, presence: true, uniqueness: { scope: :spot_id }
  validates :spot_id, presence: true
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @spot = Spot.find(params[:spot_id])
    current_user.favorite(@spot)
  end

  def destroy
    @spot = Favorite.find(params[:id]).spot
    current_user.unfavorite(@spot)
  end
end

app/views/favorites/_favorite.html.erb
<%= link_to favorites_path(spot_id: spot.id), id: "favorite_button_#{spot.id}", method: :post, remote: true do %>
  <i class="fa-regular fa-star" style="color: #1E50A2;"></i>
<% end %>

app/views/favorites/_favorite_button.html.erb
<% if logged_in? %>
  <% if current_user.favorite?(spot) %>
    <%= render partial: 'favorites/unfavorite', locals: { spot: spot } %>
  <% else %>
    <%= render partial: 'favorites/favorite', locals: { spot: spot } %>
  <% end %>
<% end %>

app/views/favorites/_unfavorite.html.erb
<%= link_to favorite_path(current_user.favorites.find_by(spot_id: spot.id).id), id: "unfavorite_button_#{spot.id}", method: :delete, remote: true do %>
  <i class="fa-solid fa-star" style="color: #1E50A2;"></i>
<% end %>

app/views/favorites/create.js.erb
document.querySelector("#favorite_button_<%= @spot.id %>").outerHTML =
  "<%= escape_javascript(render 'favorites/unfavorite', spot: @spot) %>"
;

app/views/favorites/destroy.js.erb
document.querySelector("#unfavorite_button_<%= @spot.id %>").outerHTML =
  "<%= escape_javascript(render 'favorites/favorite', spot: @spot) %>"
;