config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root to: 'home#index'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'spots_data', to: 'home#spots_data'
  get 'about', to: 'about#index'

  resource :users do
    collection do
      get 'activate'
      get 'delete_confirm'
      get 'list'
      get 'spots'
      get 'comments'
      delete 'remove'
    end
  end
  resources :spots do
    resources :comments, shallow: true, only: %i[create destroy]
    collection do
      get 'list'
      get 'favorites'
      get 'search'
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :email_changes, only: %i[create] do
    collection do
      get 'confirm'
    end
  end
  resources :password_resets, only: %i[new create edit update]
  resources :search_places, only: %i[index create]
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :spots
  has_many :comments, dependent: :nullify
  has_many :favorites, dependent: :destroy
  has_many :favorite_spots, through: :favorites, source: :spot

  enum role: { general: 0, admin: 1 }

  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 8 }, format: { with: /\A[a-zA-Z0-9]+\z/ }, confirmation: true, if: -> { password.present? || new_record? }
  validate :new_email_uniqueness, if: -> { new_email.present? }

  def favorite(spot)
    favorite_spots << spot
  end

  def unfavorite(spot)
    favorite_spots.delete(spot)
  end

  def favorite?(spot)
    favorite_spots.include?(spot)
  end

  def admin?
    role == 'admin'
  end

  def new_email_uniqueness
    if User.where(email: new_email).exists?
      errors.add(:new_email, 'このメールアドレスは既に登録されています')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create activate]
  before_action :authenticated, only: [:new]
  before_action :admin_only, only: %i[list spots comments]

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = t('helpers.flash.user.register.procedure')
      redirect_to login_path
    else
      flash.now[:danger] = t('helpers.flash.user.register.failure')
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    params_without_old_password = user_params.dup
    params_without_old_password.delete(:old_password)

    if user_params[:old_password].present? || user_params[:password].present? || user_params[:password_confirmation].present?
      if @user.valid_password?(user_params[:old_password]) && user_params[:password].present? && user_params[:password_confirmation].present?
        if @user.update(params_without_old_password)
          flash[:success] = t('helpers.flash.user.update.success')
          redirect_to users_path
        else
          flash.now[:danger] = t('helpers.flash.user.update.failure')
          render :edit
        end
      else
        case
        when user_params[:old_password].blank?
          flash.now[:danger] = '現在のパスワードを入力してください'
        when user_params[:password].blank? || user_params[:password_confirmation].blank?
          flash.now[:danger] = '「新しいパスワード」と「新しいパスワード（確認）」を入力してください'
        when !@user.valid_password?(user_params[:old_password])
          flash.now[:danger] = '現在のパスワードが正しくありません'
        else
          flash.now[:danger] = t('helpers.flash.user.update.failure')
        end
        render :edit
      end
    elsif @user.update(params_without_old_password)
      flash[:success] = t('helpers.flash.user.update.success')
      redirect_to users_path
    else
      flash.now[:danger] = t('helpers.flash.user.update.failure')
      render :edit
    end
  end

  def destroy
    @user = current_user
    if @user.valid_password?(params[:password])
      @user.destroy!
      flash[:success] = t('helpers.flash.user.destroy')
      redirect_to root_path
    else
      flash.now[:danger] = 'パスワードが正しくありません'
      render :delete_confirm
    end
  end

  def activate
    if @user = User.load_from_activation_token(params[:token])
      @user.activate!
      flash[:success] = t('helpers.flash.user.register.activate')
      redirect_to login_path
    else
      flash[:danger] = t('helpers.flash.user.register.activate_failure')
      redirect_to login_path
    end
  end

  def delete_confirm; end

  def list
    @users = User.all.order(id: :desc).page(params[:page])
  end

  def remove
    @user = User.find(params[:user_id])
    @user.destroy!
    flash[:success] = t('helpers.flash.user.destroy')
    redirect_to list_users_path
  end

  def spots
    if params[:user_id]
      @user = User.find_by(id: params[:user_id])
      @spots = @user.spots.order(id: :desc).page(params[:page])
    else
      @spots = Spot.all.order(created_at: :desc).page(params[:page])
    end
  end

  def comments
    if params[:user_id]
      @user = User.find_by(id: params[:user_id])
      @comments = @user.comments.order(id: :desc).page(params[:page])
    else
      @comments = Comment.all.order(created_at: :desc).page(params[:page])
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :old_password,
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/comments.html.erb
<% content_for :title do %>
  <title>コメント一覧 | 自転車空気入れマップ</title>
<% end %>

<main class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto mt-3 mb-5">
      <h1>コメント一覧</h1>
      <p>ユーザー名：<%= @user ? @user.name : 'すべてのユーザー' %></p>
      <div class="table-responsive">
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>施設名</th>
              <th>コメント</th>
              <th>投稿者</th>
              <th>投稿日時</th>
            </tr>
          </thead>
          <tbody>
            <% @comments.each do |comment| %>
              <tr>
                <td><%= comment.id %></td>
                <td><%= link_to comment.spot.name, spot_path(comment.spot), class: 'text-decoration-none' %></td>
                <td><%= comment.content %></td>
                <td><%= comment.user ? comment.user.name : '(匿名)' %></td>
                <td><%= comment.created_at.strftime('%Y/%m/%d %H:%M') %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="d-flex justify-content-center">
        <%= paginate @comments, theme: 'bootstrap-5' %>
      </div>
    </div>
  </div>
</main>

app/views/users/delete_confirm.html.erb
<% content_for :title do %>
  <title>アカウント削除 | 自転車空気入れマップ</title>
<% end %>

<main class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto mt-3 mb-5">
      <h1>アカウント削除</h1>
      <div class="card">
        <div class="card-body">
          <p class="card-text">
            下記のアカウントを完全に削除しようとしています。<br>削除する場合はパスワードを入力してください。
          </p>
        </div>
      </div>
      <%= form_with url: users_path, method: :delete, local: true do |f| %>
        <div class="mt-3">
          <p class="text-secondary">ハンドルネーム</p>
          <p class="ms-3"><%= current_user.name %></p>
        </div>
        <div>
          <p class="text-secondary">メールアドレス</p>
          <p class="ms-3"><%= current_user.email %></p>
        </div>
        <div class="mb-3">
          <%= f.label :password, class: 'form-label text-secondary' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <%= f.submit t('helpers.submit.delete'), class: 'btn btn-danger col-12 col-lg-2', data: { confirm: '本当に削除してよろしいですか？' } %>
      <% end %>
    </div>
  </div>
</main>

app/views/users/edit.html.erb
<% content_for :title do %>
  <title>アカウント編集 | 自転車空気入れマップ</title>
<% end %>

<main class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto mt-3 mb-5">
      <h1>アカウント情報更新</h1>
      <%= form_with model: @user, url: users_path, local: true do |f| %>
        <div class="mb-3">
          <%= f.label :name, class: 'form-label text-secondary' %>
          <%= f.text_field :name, class: 'form-control' %>

          <% if @user.errors.include?(:name) %>
            <p class="text-danger"><%= @user.errors[:name].first %></p>
          <% end %>
        </div>
        <div class="mb-3">
          <%= f.label :old_password, '現在のパスワード（パスワードを変更したい場合のみ入力してください）', class: 'form-label text-secondary' %>
          <%= f.password_field :old_password, class: 'form-control' %>
        </div>
        <div class="mb-3">
          <%= f.label :password, '新しいパスワード（半角英数字8文字以上）', class: 'form-label text-secondary' %>
          <%= f.password_field :password, class: 'form-control' %>

          <% if @user.errors.include?(:password) %>
            <p class="text-danger"><%= @user.errors[:password].first %></p>
          <% end %>
        </div>
        <div class="mb-3">
          <%= f.label :password_confirmation, '新しいパスワード（確認）', class: 'form-label text-secondary' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>

          <% if @user.errors.include?(:password_confirmation) %>
            <p class="text-danger"><%= @user.errors[:password_confirmation].first %></p>
          <% end %>
        </div>
        <%= f.submit t('helpers.submit.update'), class: 'btn btn-primary col-12 col-lg-2' %>
      <% end %>

      <hr class="mt-4">

      <h1>メールアドレス変更</h1>
      <div class="card">
        <div class="card-body">
          <p class="card-text">
            送信ボタンを押下すると認証メールが届きます。<br>
            メール内のリンクをクリックするまで、メールアドレスは変更されません。<br>
            メールが受信できない場合、迷惑メールに振り分けられていないかご確認お願いいたします。
          </p>
        </div>
      </div>
      <div class="mb-3 mt-3">
        <p class="text-secondary">現在のメールアドレス</p>
        <p class="ms-3"><%= @user.email %></p>
      </div>
      <%= form_with url: email_changes_path, local: true do |f| %>
        <div class="mb-3">
          <%= f.label :new_email, '新しいメールアドレス', class: 'form-label text-secondary' %>
          <%= f.email_field :new_email, class: 'form-control', required: true %>

          <% if @user.errors.include?(:new_email) %>
            <p class="text-danger"><%= @user.errors[:new_email].first %></p>
          <% end %>
        </div>
        <%= f.submit t('helpers.submit.send'), class: 'btn btn-primary col-12 col-lg-2' %>
      <% end %>
    </div>
  </div>
</main>

app/views/users/list.html.erb
<% content_for :title do %>
  <title>ユーザー一覧 | 自転車空気入れマップ</title>
<% end %>

<main class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto mt-3 mb-5">
      <h1>ユーザー一覧</h1>
      <div class="table-responsive">
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>ハンドルネーム</th>
              <th>メールアドレス</th>
              <th>登録日時</th>
              <th>登録施設数</th>
              <th>コメント数</th>
              <th>管理者</th>
              <th>削除</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.id %></td>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><%= user.created_at.strftime('%Y/%m/%d %H:%M') %></td>
                <td class="text-center">
                  <% if user.spots.count == 0 %>
                    <%= user.spots.count %>
                  <% else %>
                    <%= link_to user.spots.count, spots_users_path(user_id: user.id), class: 'text-decoration-none' %>
                  <% end %>
                <td class="text-center">
                  <% if user.comments.count == 0 %>
                    <%= user.comments.count %>
                  <% else %>
                    <%= link_to user.comments.count, comments_users_path(user_id: user.id), class: 'text-decoration-none' %>
                  <% end %>
                </td>
                <td class="text-center"><%= user.admin? ? '○' : '' %></td>
                <td>
                  <% if user != current_user %>
                    <%= link_to t('helpers.submit.delete'), remove_users_path(user_id: user.id), method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="d-flex justify-content-center">
        <%= paginate @users, theme: 'bootstrap-5' %>
      </div>
    </div>
  </div>
</main>

app/views/users/new.html.erb
<% content_for :title do %>
  <title>新規アカウント登録 | 自転車空気入れマップ</title>
<% end %>

<main class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto mt-3 mb-5">
      <h1>新規アカウント登録</h1>
      <div class="card">
        <div class="card-body">
          <p class="card-text">
            登録ボタンを押下すると認証メールが届きます。<br>
            メール内のリンクをクリックするまで、アカウントは有効化されません。<br>
            メールが受信できない場合、迷惑メールに振り分けられていないかご確認お願いいたします。
          </p>
        </div>
      </div>
      <%= form_with model: @user, local: true do |f| %>
        <div class="mb-3 mt-3">
          <%= f.label :name, class: 'form-label' %>
          <%= f.text_field :name, class: 'form-control' %>

          <% if @user.errors.include?(:name) %>
            <p class="text-danger"><%= @user.errors[:name].first %></p>
          <% end %>
        </div>
        <div class="mb-3">
          <%= f.label :email, class: 'form-label' %>
          <%= f.email_field :email, class: 'form-control' %>

          <% if @user.errors.include?(:email) %>
            <p class="text-danger"><%= @user.errors[:email].first %></p>
          <% end %>
        </div>
        <div class="mb-3">
          <%= f.label :password, class: 'form-label' %>
          <%= f.password_field :password, class: 'form-control' %>

          <% if @user.errors.include?(:password) %>
            <p class="text-danger"><%= @user.errors[:password].first %></p>
          <% end %>
        </div>
        <div class="mb-3">
          <%= f.label :password_confirmation, class: 'form-label' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>

          <% if @user.errors.include?(:password_confirmation) %>
            <p class="text-danger"><%= @user.errors[:password_confirmation].first %></p>
          <% end %>
        </div>
        <%= f.submit t('helpers.submit.register'), class: 'btn btn-primary col-12 col-lg-2' %>
      <% end %>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<% content_for :title do %>
  <title>アカウント | 自転車空気入れマップ</title>
<% end %>

<main class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto mt-3 mb-5">
      <h1>アカウント</h1>
      <div>
        <p class="text-secondary">ハンドルネーム</p>
        <p class="ms-3"><%= current_user.name %></p>
      </div>
      <div>
        <p class="text-secondary">メールアドレス</p>
        <p class="ms-3"><%= current_user.email %></p>
      </div>
      <div>
        <p class="text-secondary">アカウント登録日</p>
        <p class="ms-3"><%= current_user.created_at.strftime('%Y/%m/%d') %></p>
      </div>
      <div>
        <%= link_to edit_users_path do %>
          <button class="btn btn-primary col-12 col-lg-2">編集</button>
        <% end %>
      </div>
      <div class="d-flex justify-content-end mt-3">
        <%= link_to 'アカウント削除はこちら', delete_confirm_users_path, class: 'text-decoration-none' %>
      </div>
    </div>
  </div>
</main>

app/views/users/spots.html.erb
<% content_for :title do %>
  <title>登録施設一覧 | 自転車空気入れマップ</title>
<% end %>

<main class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto mt-3 mb-5">
      <h1>登録施設一覧</h1>
      <p>ユーザー名：<%= @user ? @user.name : 'すべてのユーザー' %></p>
      <div class="table-responsive">
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>施設名</th>
              <th>住所</th>
              <th>登録者</th>
              <th>登録日時</th>
            </tr>
          </thead>
          <tbody>
            <% @spots.each do |spot| %>
              <tr>
                <td><%= spot.id %></td>
                <td><%= link_to spot.name, spot_path(spot), class: 'text-decoration-none' %></td>
                <td><%= spot.decorate.full_address %></td>
                <td><%= spot.user ? spot.user.name : '(匿名)' %></td>
                <td><%= spot.created_at.strftime('%Y/%m/%d %H:%M') %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="d-flex justify-content-center">
        <%= paginate @spots, theme: 'bootstrap-5' %>
      </div>
    </div>
  </div>
</main>