config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root to: 'home#index'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'spots_data', to: 'home#spots_data'
  get 'about', to: 'about#index'

  resource :users do
    collection do
      get 'activate'
      get 'delete_confirm'
      get 'list'
      get 'spots'
      get 'comments'
      delete 'remove'
    end
  end
  resources :spots do
    resources :comments, shallow: true, only: %i[create destroy]
    collection do
      get 'list'
      get 'favorites'
      get 'search'
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :email_changes, only: %i[create] do
    collection do
      get 'confirm'
    end
  end
  resources :password_resets, only: %i[new create edit update]
  resources :search_places, only: %i[index create]
end

app/views/shared/_before_login_header.html.erb
<header id="header">
  <nav class="navbar navbar-dark">
    <div class="container-fluid">
      <button class="navbar-toggler hover-opacity" type="button" data-bs-toggle="offcanvas" data-bs-target="#menu">
        <i class="fa-solid fa-bars fa-lg text-white"></i>
      </button>
      <div class="offcanvas offcanvas-start" id="menu" style="width: 300px;">
        <div class="offcanvas-header">
          <p class="offcanvas-title h4">MENU</p>
          <button class="btn-close text-reset" type="button" data-bs-dismiss="offcanvas"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav">
            <li class="nav-item row align-items-center">
              <i class="fa-solid fa-circle-info text-black col-2"></i>
              <%= link_to 'サービスについて', '#', class: 'nav-link link-dark col hover-underline' %>
            </li>
            <li class="nav-item row align-items-center">
              <i class="fa-solid fa-house text-black col-2"></i>
              <%= link_to 'トップページ', root_path, class: 'nav-link link-dark col hover-underline' %>
            </li>
            <li class="nav-item row align-items-center">
              <i class="fa-solid fa-magnifying-glass text-black col-2"></i>
              <%= link_to '施設検索', '#', class: 'nav-link link-dark col hover-underline' %>
            </li>
            <li class="nav-item row align-items-center">
              <i class="fa-solid fa-magnifying-glass-location text-black col-2"></i>
              <%= link_to '地名検索', '#', class: 'nav-link link-dark col hover-underline' %>
            </li>
            <li class="nav-item row align-items-center">
              <i class="fa-solid fa-list text-black col-2"></i>
              <%= link_to '施設一覧', '#', class: 'nav-link link-dark col hover-underline' %>
            </li>
            <li class="nav-item row align-items-center">
              <i class="fa-solid fa-user text-black col-2"></i>
              <%= link_to 'アカウント', '#', class: 'nav-link link-dark col hover-underline' %>
            </li>
            <li class="nav-item row align-items-center">
              <i class="fa-solid fa-table-list text-black col-2"></i>
              <%= link_to '登録した施設', '#', class: 'nav-link link-dark col hover-underline' %>
            </li>
            <li class="nav-item row align-items-center">
              <i class="fa-solid fa-star text-black col-2"></i>
              <%= link_to 'お気に入り', '#', class: 'nav-link link-dark col hover-underline' %>
            </li>
          </ul>
        </div>
      </div>

      <h1><%= link_to '自転車空気入れマップ', root_path, class: 'navbar-brand hover-opacity' %></h1>

      <%= link_to '#' do %>
        <i class="fa-solid fa-arrow-right-to-bracket fa-2x text-white hover-opacity"></i>
      <% end %>
    </div>
  </nav>
</header>

app/views/shared/_flash_message.html.erb
<div class="alert-container col-10 col-md-9 col-lg-3">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %> alert-dismissible">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<header id="header" class="fixed-top">
  <nav class="navbar navbar-dark">
    <div class="container-fluid">
      <div>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#menu">
          <i class="fa-solid fa-bars fa-lg text-white"></i>
        </button>
      </div>
      <div class="offcanvas offcanvas-start" id="menu" style="width: 300px;">
        <div class="offcanvas-header">
          <p class="offcanvas-title h4">MENU</p>
          <button class="btn-close text-reset" type="button" data-bs-dismiss="offcanvas"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav">
            <li class="nav-item row align-items-center">
              <i class="fa-solid fa-circle-info text-black col-2"></i>
              <%= link_to 'サービスについて', about_path, class: 'nav-link link-dark col hover-underline' %>
            </li>
            <li class="nav-item row align-items-center">
              <i class="fa-solid fa-house text-black col-2"></i>
              <%= link_to 'トップページ', root_path, class: 'nav-link link-dark col hover-underline' %>
            </li>
            <li class="nav-item row align-items-center">
              <i class="fa-solid fa-magnifying-glass text-black col-2"></i>
              <%= link_to '施設検索', search_spots_path, class: 'nav-link link-dark col hover-underline' %>
            </li>
            <li class="nav-item row align-items-center">
              <i class="fa-solid fa-magnifying-glass-location text-black col-2"></i>
              <%= link_to '地名検索', search_places_path, class: 'nav-link link-dark col hover-underline' %>
            </li>
            <li class="nav-item row align-items-center">
              <i class="fa-solid fa-list text-black col-2"></i>
              <%= link_to '施設一覧', spots_path, class: 'nav-link link-dark col hover-underline' %>
            </li>
            <% if logged_in? %>
              <li class="nav-item row align-items-center">
                <i class="fa-solid fa-map-location-dot text-black col-2"></i>
                <%= link_to 'あなたの登録した施設', list_spots_path, class: 'nav-link link-dark col hover-underline' %>
              </li>
              <li class="nav-item row align-items-center">
                <i class="fa-solid fa-star text-black col-2"></i>
                <%= link_to 'お気に入り', favorites_spots_path, class: 'nav-link link-dark col hover-underline' %>
              </li>
              <% if current_user.admin? %>
                <li class="nav-item row align-items-center">
                  <i class="fa-solid fa-user text-black col-2"></i>
                  <%= link_to 'ユーザー一覧（管理）', list_users_path, class: 'nav-link link-dark col hover-underline' %>
                </li>
                <li class="nav-item row align-items-center">
                  <i class="fa-solid fa-table-list text-black col-2"></i>
                  <%= link_to '登録施設一覧（管理）', spots_users_path, class: 'nav-link link-dark col hover-underline' %>
                </li>
                <li class="nav-item row align-items-center">
                  <i class="fa-solid fa-comments text-black col-2"></i>
                  <%= link_to 'コメント一覧（管理）', comments_users_path, class: 'nav-link link-dark col hover-underline' %>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>

      <div>
        <h1>
          <%= link_to '自転車空気入れマップ', root_path, class: 'navbar-brand hover-opacity mx-0' %>
        </h1>
      </div>

      <div>
        <% if logged_in? %>
          <div class="dropdown">
            <button class="btn dropdown-toggle text-white" type="button" id="dropdownMenu" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa-regular fa-circle-user fa-2xl text-white"></i>
            </button>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenu">
              <li>
                <%= link_to 'アカウント', users_path, class: 'dropdown-item' %>
              </li>
              <li>
                <%= link_to 'ログアウト', logout_path, class: 'dropdown-item', method: :delete %>
              </li>
            </ul>
          </div>
        <% else %>
          <div class="login-icon">
            <%= link_to login_path do %>
              <i class="fa-solid fa-arrow-right-to-bracket fa-2xl text-white"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </nav>
</header>